### ISSUE TITLE
Conflicting naming

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/logic-introduction#36]
In chapter 11 and its appendix, there are three completely independent occurrences of "11.7.1", and also of "11.7.2". For most other numbers there are two occurrences. This is confusing when trying to refer to a separate part, so I think this should be resolved somehow. Perhaps by including a fourth point (eg. 11.7.2.1).

**Comment by jkorb** [comment]
Oh, thanks @607GitHub ! That's a stupid error in my code, it should indeed have been 1.7.2.1 (which I get by setting \begin{enumerate}[\thesection.\thesubsection.1] but I wrote \begin{enumerate}[\thesection.1]). About to fix it.
