### ISSUE TITLE
Typo 5.1.9

### ISSUE THREAD

**Issue by Thovex** [jkorb/logic-introduction#4]
in ```tex/mainmatter/prop-semantics.tex``` line 193

```\llbracket \neg (p\land (p\lor q))\rrbracket_v &=1-\llbracket (p\land (r\lor q))\rrbracket_v\tag{ii.a}\\``` should be:
```\llbracket \neg (p\land (r\lor q))\rrbracket_v &=1-\llbracket (p\land (r\lor q))\rrbracket_v\tag{ii.a}\\```

(p should be r before equals)

**Comment by jkorb** [comment]
Thanks, @Thovex !
