### ISSUE TITLE
Missing item labels and incomplete solutions to 10.8.2c,d

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/logic-introduction#44]
Okay, my final judgment for now: (the rest was edited out to be less confusing)
The first unlabeled item after 10.8.2a and b in Appendix J, is a solution to 10.8.2d. However, the countermodel given is infinite, which is not allowed. A finite countermodel would be D = {p1, p2}, S = {<p1, p2>, <p2, p1>}. I'm not sure what the second unlabeled item is, but there is no solution for c. The solution for c has one closed branch and one open branch, and a finite countermodel is D = {p, q}, P = {p}, Q = emptyset.

**Comment by jkorb** [comment]
Thanks @607GitHub . This bamboozled me for a sec but I think now I got it: there are actually 3 (!) things wrong...

(1) There's a latex bug where I closed the enumerate too early (easy fix: 89e6aff)
(2) The solution to (c) was missing (I'll add it)
(3) The tableau for (e) is actually for the conditional formed from permises to conclusion (weird but easy fix) and is missing an explanation for the model. 

Note that infinite models _are_ allowed, the question just asks to provide a finite one if possible. Yours works very well, so I'll add it :)
