### ISSUE TITLE
Typo's chapter 9

### ISSUE THREAD

**Issue by mvrozend** [jkorb/logic-introduction#52]
**9.1.2**
"Note that a model for propositional logic, i.e. a assignment," should be "Note that a model for propositional logic, i.e. an assignment,"

**9.1.12**
"The problem is has very much to do with what happens when we have more than one quantifier in a statement" should be "The problem has very much to do with what happens when we have more than one quantifier in a statement"

"our intended momdel," should be "our intended model,"

"While there is a assignment β such that" should be "while there is an assignment β such"

**9.2.10**
"i.e. terms of the of the form n=S(...S(0)...)." should be "i.e. terms of the form n=S(...S(0)...). "

**9.3.2**
"we can define truth in a model under **a** assignment as  a property of  formulas." should be "we can define truth in a model under **an** assignment as  a property of  formulas."

**Comment by jkorb** [comment]
Thanks @mvrozend !
