### ISSUE TITLE
1 missing closing parenthesis in solution 11.7.1.4 (APPENDIX K)

### ISSUE THREAD

**Issue by ercanoezii** [jkorb/logic-introduction#53]
The line below of solution 11.7.1.4 misses one closing parentheses at the end (page 358)
> M, alpha |= AxAy(R(x, y) --> R(f(y), f(x))

**Comment by ercanoezii** [comment]
On the next page of the same solution (11.7.1.4 ), in the line 
>But then, we have M, alpha [x |-> d, y |-> d' |= R(f(y), f(x)) ...

there misses an ] to close the [x |-> d, y |-> d' part.

**Comment by jkorb** [comment]
Thanks @ercanoezii ! 👍
