### ISSUE TITLE
The solution of 11.7.2.8 doesn't show the question number, but a bullet point (APPENDIX K)

### ISSUE THREAD

**Issue by ercanoezii** [jkorb/logic-introduction#55]
On page 367 you see a bullet point instead of 11.7.2.8 (see screenshot)

![image](https://user-images.githubusercontent.com/71670946/97110947-428bb380-16dc-11eb-8a6b-11566a599d62.png)

**Comment by jkorb** [comment]
Thanks @ercanoezii : another one 👍

**Comment by jkorb** [comment]
I fixed this in 971a009 but wrote a bad commit message :(
