### ISSUE TITLE
Typo pagina 144

### ISSUE THREAD

**Issue by rubenvdz** [jkorb/logic-introduction#6]
Op pagina 144 staat twee keer: 
[[p ∨ q]]v = max([[p]]v, [[p]]v)

I.p.v. 
[[p ∨ q]]v = max([[p]]v, [[q]]v)

**Comment by jkorb** [comment]
Thanks @rubenvdz ! Next time, could you tell me the item number (this one is in 6.2.5.d) or line number in the .tex file? This makes it easier for me to spot the typo. Thanks :)
