### ISSUE TITLE
Mistake in solution for 11.7.1.5

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/logic-introduction#61]
In appendix K, the tableau for the first part of exercise 5 of part A has at its right branch a negation where there shouldn't be one. With this mistake in place, the branch actually should remain open (but it does indeed close if you leave out the negation).

**Comment by jkorb** [comment]
Thanks @607GitHub ! We spotted this in the Q&A yesterday and I fixed it already this morning in 880edad
