### ISSUE TITLE
Tree branche is not closed

### ISSUE THREAD

**Issue by rooslucas** [jkorb/logic-introduction#7]
Op pagina 148 van het dictaat onderdeel van 6.3.2 stap 3 wordt er gesteld dat een branche gesloten is als p ∈ P such that p ∈ B and ¬p ∈ B. Nu staat er in het voorbeeld een tak die gesloten is van r, maar de enige r die erin zitten zijn ¬¬¬r en ¬r. De tak hoort dan toch niet gesloten te zijn?
<img width="459" alt="Screenshot 2020-09-24 at 11 46 06" src="https://user-images.githubusercontent.com/38834220/94130186-9cd6f180-fe5c-11ea-9a19-2e74dbe1978f.png">

**Comment by jkorb** [comment]
Dank @rooslucas . De taak is niet gesloten vanwege ¬¬¬r en ¬r maar vanwege p en ¬p verder boven in de taak. De taken in dit tableau zijn volledig uitgewerkt ook nadat al duidelijk was dat ze uiteindelijk afgesloten moeten werken (no early closing). Het is dus alleen belangrijk of je als je van het einde (¬r in dit geval) naar de oorsprong (p^q) gaat twee formules p en ¬p tegenkomt; en dat doe je dus is de tak correct afgesloten :)

**Comment by rooslucas** [comment]
Ik begrijp het bedankt!
