### ISSUE TITLE
Typo in 5.1.9

### ISSUE THREAD

**Issue by coenvdam** [jkorb/logic-introduction#8]
`/tex/mainmatter/prop-semantics.tex` on line 181 `\item  $\llbracket\neg \phi\rrbracket_v=1-\llbracket\phi\rrbracket_v)$` should be one of the following:

- `\item  $\llbracket\neg \phi\rrbracket_v=(1-\llbracket\phi\rrbracket_v)$`
- `\item  $\llbracket\neg \phi\rrbracket_v=1-\llbracket\phi\rrbracket_v$`

**Comment by jkorb** [comment]
Thanks @coenvdam ! Great work, keep it up :)
